## Create 1 course
POST http://localhost:3000/courses
Content-Type: application/json

{
    "title": "NestJs"
 
}


###

GET http://localhost:3000/courses

#### Create 1 user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "test@gmail.com",
  "username": "tester69",
  "password": "Tester69"
}