## Create 1 course
POST http://localhost:3000/courses
Content-Type: application/json

{
    "title": "NestJs"
 
}


###

GET http://localhost:3000/courses

#### Sign up
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "test@gmail.com",
  "username": "tester69",
  "password": "Tester69"
}
### Login
POST http://localhost:3000/auth/log-in
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Tester69"
}

### Logout
POST http://localhost:3000/auth/log-out


